#!/usr/bin/env python


def build(bld):
    bld.program(
        includes="../src/",
        source=[
            'runner.c',
            'test_bounds.c',
            'test_integration.c',
            'test_vector_layer.c',
            'test_raster_layer.c',
            'test_list.c',
            'test_map.c',
            'test_query.c',
            'test_style.c'
        ],
        use='simple-tiles',
        target='runner',
        uselib='CAIRO GDAL M GL',
        install_path=None
    )

    bld.program(
        includes="../src/",
        source='api.c',
        use='simple-tiles',
        target='api',
        uselib='CAIRO GDAL M GL',
        install_path=None
    )

    bld.program(
        includes="../src/",
        source='benchmark.c',
        use='simple-tiles',
        target='benchmark',
        uselib='CAIRO GDAL M GL',
        install_path=None
    )
